"use client";

import Link from "next/link";

import { FaShoppingCart } from "react-icons/fa";
import { useSelector } from "react-redux";

const Header = () => {
  const cartItems = useSelector((state) => state.cart.items);
  return (
    <div className="w-[100vw] h-[120px] border-b-2">
      {/* Header Messages */}
      <div className="w-full h-[30%] flex justify-center items-center bg-[var(--border-color)]">
        <h1 className="text-[var(--main-color)]">
          All Products are generated by ChatGPT!
        </h1>
      </div>
      <div className="flex h-[70%] w-full justify-between items-center px-[5vw]">
        <Link
          href="/"
          className="text-[var(--border-color)] text-[2vw] font-Raleway"
        >
          VIDA GLOW
        </Link>
        <div className="w-[50%] flex justify-evenly">
          <p>JOURNAL</p>
          <Link href="/feedback">FEEDBACK</Link>
          <Link href="/about">ABOUT US</Link>
        </div>
        <Link href="/cart" className="flex justify-center items-center gap-1">
          <FaShoppingCart className="text-[2vw]" />
          <p className="w-[2vw] h-[2vw] text-center leading-[2vw] rounded-full bg-[var(--border-color)] text-[var(--main-color)]">
            {cartItems.length}
          </p>
        </Link>
      </div>
    </div>
  );
};

export default Header;
