"use client";

import Link from "next/link";

import { FaShoppingCart } from "react-icons/fa";
import { useSelector } from "react-redux";
import { usePathname } from "next/navigation";

const Header = () => {
  const pathname = usePathname();
  console.log(pathname);
  const cartItems = useSelector((state) => state.cart.items);
  return (
    <div className="w-[100vw] h-[120px] border-b-2">
      {/* Header Messages */}
      <div className="w-full h-[20%] md:h-[30%] flex justify-center items-center bg-[var(--border-color)]">
        <h1 className="text-[var(--main-color)] text-[3vw] md:text-[1vw]">
          All Products are generated by ChatGPT
        </h1>
      </div>
      {/* header links PC */}
      <div className="flex h-[60%] md:h-[70%] w-full justify-between items-center px-[5vw]">
        <Link
          href="/"
          className="text-[var(--border-color)] text-[4vw] md:text-[2vw] font-Raleway"
        >
          VIDA GLOW
        </Link>
        <div className="hidden md:flex w-[50%] justify-evenly">
          <Link
            href="/journal"
            className={pathname === "/journal" ? "font-bold" : ""}
          >
            JOURNAL
          </Link>
          <Link
            href="/feedback"
            className={pathname === "/feedback" ? "font-bold" : ""}
          >
            FEEDBACK
          </Link>
          <Link
            href="/about"
            className={pathname === "/about" ? "font-bold" : ""}
          >
            ABOUT US
          </Link>
        </div>
        {/* cart */}
        <Link href="/cart" className="flex justify-center items-center gap-1">
          <FaShoppingCart className="text-[5vw] md:text-[2vw]" />
          <p className="w-[5vw] h-[5vw] md:w-[2vw] md:h-[2vw] text-center leading-[5vw] md:leading-[2vw] rounded-full bg-[var(--border-color)] text-[var(--main-color)]">
            {cartItems.length}
          </p>
        </Link>
      </div>
      <hr className="block md:hidden" />
      <div className="flex md:hidden w-full h-[20%] justify-evenly text-[3vw] items-center">
        <Link
          href="/journal"
          className={pathname === "journal" ? "font-bold" : ""}
        >
          JOURNAL
        </Link>
        <Link
          href="/feedback"
          className={pathname === "/feedback" ? "font-bold" : ""}
        >
          FEEDBACK
        </Link>
        <Link
          href="/about"
          className={pathname === "/about" ? "font-bold" : ""}
        >
          ABOUT US
        </Link>
      </div>
    </div>
  );
};

export default Header;
