import { Oswald, Orbitron, Raleway } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import { Toaster } from "@/components/ui/toaster";

import Header from "./components/Header";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  weight: "400",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  weight: "600",
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: "600",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${oswald.variable} ${orbitron.variable} ${raleway.variable} overflow-x-hidden`}
        >
          <Header />
          {children}
          <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
